import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'
import { HeartIcon, HomeIcon, SearchIcon } from 'lucide-react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <div className='fixed bottom-0 w-full bg-black py-6 text-white'>
          <nav className='flex justify-evenly'>
            <Link href='/'>
              <div>
                <HomeIcon size={24} />
              </div>
            </Link>
            <Link href='/search'>
              <div>
                <SearchIcon size={24} color='grey' />
              </div>
            </Link>
            <Link href='/favorites'>
              <div>
                <HeartIcon size={24} color='grey' />
              </div>
            </Link>
          </nav>
        </div>
      </body>
    </html>
  )
}
